services:
  yap:
    build:
      context: ./Yap
      dockerfile: Dockerfile
    ports:
      - "5221:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./uploads:/app/wwwroot/uploads
      - ./data:/app/Data
    restart: unless-stopped
