version: '3.8'

services:
  blazorchat-server:
    image: ghcr.io/${GITHUB_USER}/blazorchat-server:latest
    container_name: blazorchat-server
    ports:
      - "5224:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./uploads:/app/wwwroot/uploads
    restart: unless-stopped

  blazorchat:
    image: ghcr.io/${GITHUB_USER}/blazorchat-client:latest
    container_name: blazorchat
    ports:
      - "5221:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiUrl=http://localhost:5224
    depends_on:
      - blazorchat-server
    restart: unless-stopped

networks:
  default:
    name: blazorchat-network