services:
  yap:
    build:
      context: ./Yap
      dockerfile: Dockerfile
    ports:
      - "5221:5221"
    environment:
      - ASPNETCORE_URLS=http://+:5221
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./uploads:/app/wwwroot/uploads
    restart: unless-stopped
